import 'package:flutter/material.dart';

class ManagerColors {
  static const Color white = Colors.white;
  static const Color greyWhite = Color(0xffF6F6F6);
  static const Color green = Color(0xff38E54D);
  static const Color black = Colors.black;
  static const Color textColor = Color(0xFF072A33);
  static const Color textColorLight = Color(0xff525167);
  static const Color subTitleColor = Color(0xff839499);
  static const Color primaryColor = Color(0xffDA2F37);
  static const Color oldPrimaryColor = Color(0xffFFB300);
  static const Color borderSide = Color(0xff1A1919);
  static const Color buttonColorLight = Colors.black;
  static const Color buttonColorDarK = Color(0xFFA7E4DC);
  static const Color forgetTextColor = Color(0xff1CA0BF);
  static const Color greyLight = Color(0xFFD5D5D5);
  static const Color primaryColorDark = Color(0xFFB8C9CC);
  static const Color primaryColorLight = Color(0xFF000333);
  static const Color background = Color(0xFFF2F7F7);
  static const Color backgroundForm = Color(0xFFFBFBFE);
  static const Color grey = Color(0xFFB4B8BD);
  static const Color greyDark = Color(0xFF454545);
  static const Color backgroundCategory = Color(0xFEDD6800);
  static const Color backgroundCategories = Color(0xFFF1F1F1);
  static const Color selectedCategory = Color(0xFFFFC727);
  static const Color backgroundCourses = Color(0xffFFF3F3);
  static const Color textColorProfile = Color(0xff737373);
  static const Color activeSwitchColor = Color(0xff4CD964);
  static const Color textColorAppoint = Color(0xff928F8E);
  static const Color activationStatus = Color(0xffCACACA);
  static const Color completedStatus = Color(0xff30C165);
  static const Color cancelledStatus = Color(0xffF05353);
  static const Color searchColor = Color(0xffADADAD);
  static const Color descriptionColor = Color(0xff6A7F84);
  static const Color scaffoldBackgroundColorLight = Colors.white;
  static const Color snackBarErrorColor = Colors.red;
  static const Color activeColorIndicator = ManagerColors.primaryColor;
  static const Color inactiveColorIndicator = Colors.grey;
  static const Color textColorblackButton = Colors.white;
  static const Color transparent = Colors.transparent;
  static const Color fillInputVerification = Color.fromARGB(0, 163, 40, 40);
  static const Color focusedBorderInputVerification = primaryColor;
  static const Color enabledBorderInputVerification = Colors.grey;
  static const Color appBarLightBackground = Colors.white;
}
